### PR TITLE
Data model

### PR DESCRIPTION
**Pull request by Cluab**
### Completed Project requirements

- Create a new app. Give it a meaningful name.
- Initialize your project with Git.
- Make sure that your project has Postgres database set up.
- Build your project schema.
    - Create and run the necessary migration files.
    - Table and column names should match the ERD diagram.
        - note: photo for users table should be a link to an image
    - Foreign keys should be included.
    - All columns that are foreign keys should have a corresponding index.

### CODE REVIEW

**Comment by Cluab** [comment]
## Hello There C.R

### why isn't robocop performing checks and what's up with all of the stylelint errors fixing them will take forever can you help out i didn't change anything in the code just created the rails project and added the schema

**Comment by rloterh** [comment]
Hello @Cluab 

Let's first examine the root of the errors. Click on the _details_ of each linter check to find out what's going wrong.

image

From there we can see a number of linter offenses coming from our code.
For Stylint, we can attempt auto fixing errors using the command 
`npx stylelint "**/*.{css,scss}" --fix` or ``npx stylelint --fix`

To attempt auto-fixing Rubocop offenses, run the command `rubocop -A`

**Clicking the Stylelint checks details on the PR:**
image

**Clicking the Rubocop checks details on the PR:**
image

After running the auto-fix for each linter, if other few errors exists try to correct your code/fix manually or simply google the offense warning for solutions.

Ensure that linter errors are not showing on your local code editor before pushing the changes.

If checks are still failing on your Pull Request, I urge you to do clean installation of linters, by carefully following a step by instructions via [this link](https://github.com/microverseinc/linters-config/tree/master/ror)

**Comment by rloterh** [comment]
Hey @Cluab !
Nice job 🙌 
I noticed you fixed linters!

Congrats! 😃

**Review by rloterh — COMMENTED** [review]
Hi Cluab

While you made a great effort in this project, unfortunately, I cannot proceed to review your code.

## Invalid Code Review Request

Kindly ensure that your ReadMe is professionally documented, and adhere(s) to the following standard(s):
- [x]  The _Future Features_ section of your ReadMe includes 1-3 potential features to be added later. 
- [x] Kindly ensure that provided placeholder texts/ guide instructions are removed and/or replaced with appropriate contents applicable under each section of your ReadMe. 

Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

--------

_Invalid Code Review Request **does not count** into the code reviews limit._

**Review by Davidosky007 — APPROVED** [review]
Hi @Cluab 👋 , 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

## Highlights
* No linter errors 👍 
* Well written PR description 👍 
* Good looking readme file 👍 
## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Pull request merged**
